# Generated by Django 5.0 on 2023-12-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
                ('category', models.CharField(max_length=250, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('name', 'category'),
            },
        ),
    ]
