# Generated by Django 5.0 on 2024-01-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservice', '0003_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата приёма')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medservice.category', verbose_name='Направление')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medservice.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Приём',
            },
        ),
    ]
