# Generated by Django 5.0 on 2024-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservice', '0006_alter_appointment_category_alter_appointment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время приёма'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма'),
        ),
    ]
