# Generated by Django 5.0 on 2024-01-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservice', '0007_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='иконка'),
        ),
    ]
